version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    labels: ['release']
    target-branch: "release-0.8"
    ignore:
      - update-types: patch

  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "weekly"
    labels: ['release']
    target-branch: "release-0.8"
    ignore:
      - update-types: patch

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ['release']
    target-branch: "release-0.8"
    ignore:
      - update-types: patch

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
