name: Go
on:
  pull_request:
  push:
    branches:
      - 'release-*'
      - 'main'
    tags:
      - 'v*'
env:
  golang-version: '1.17'
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  go:
    runs-on: ubuntu-latest
    name: Go
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
        with:
          go-version-file: 'go.mod'
      - run: mkdir -p ui/build && touch ui/build/empty
      - run: make test
      - run: make pyrra
